default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    scan(
      project: "./FinanceNewsApp/FinanceNewsApp.xcodeproj",
      scheme: "FinanceNewsApp",
      clean: true,
      xcodebuild_formatter: "xcpretty",
      code_coverage: true
    )
    slather(
      proj: "./FinanceNewsApp/FinanceNewsApp.xcodeproj",
      scheme: "FinanceNewsApp",
      output_directory: "fastlane/coverage",
      github: true,
      cobertura_xml: true,
      source_directory: "./FinanceNewsApp",
      ignore: ["Pods", "Tests", ".*GeneratedAssetSymbols.swift"],
      verbose: true
    )
  end
end

